services:
  mini:
    build: .
    volumes:
      - .:/root/minishell
      - /Users/ebarayuuga/.ssh:/root/.ssh
      - /etc/localtime:/etc/localtime/:ro
    tty: true
    stdin_open: true
    #cap_add:
    #  - SYS_PTRACE
    #environment:
    #  - ROSETTA_DEBUGSERVER_PORT=1234
